# Generated by Django 2.2.1 on 2021-08-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_subscriptions', '0003_auto_20210820_0626'),
        ('purchases', '0002_auto_20200406_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='att_sub',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sprint_sub',
        ),
        migrations.AddField(
            model_name='purchase',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.Subscription'),
        ),
    ]
