# Generated by Django 2.2.1 on 2021-08-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att_subscriptions', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='attsubscription',
            name='user',
        ),
    ]
