# Generated by Django 2.2.1 on 2022-12-23 13:02

import itertools

from django.db import migrations

from wingtel.usage.selectors import (
    get_data_usage_records_group_by,
    get_voice_usage_records_group_by,
)


def add_usage_records(apps, *args):
    UsageRecord = apps.get_model("usage", "UsageRecord")
    results = []
    instances = itertools.chain(get_data_usage_records_group_by(), get_voice_usage_records_group_by())
    for record in instances:
        usage_record = UsageRecord(
            type_of_usage=record["type_of_usage"],
            subscription_id=record["subscription_id"],
            price=record["total_price"],
            usage_date=record["usage_date__date"],
            used=record["total_used"],
        )
        results.append(usage_record)
        if len(results) % 1000 == 0:
            UsageRecord.objects.bulk_create(results)
    if len(results):
        UsageRecord.objects.bulk_create(results)


def delete_usage_records(apps, *args):
    UsageRecord = apps.get_model("usage", "UsageRecord")
    UsageRecord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_usage_records, delete_usage_records)]
