# Generated by Django 2.2.1 on 2021-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BothUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField()),
                ('type_of_usage', models.CharField(choices=[('data', 'DataUsage'), ('voice', 'VoiceUsage')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usage_date', models.DateField()),
                ('used', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datausagerecord',
            name='usage_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voiceusagerecord',
            name='usage_date',
            field=models.DateTimeField(),
        ),
    ]
