# Generated by Django 2.2.1 on 2022-12-25 10:47

from django.db import migrations

from wingtel.usage.utils import read_file_to_string


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_add_usage_records"),
    ]

    create_views_file = "wingtel/usage/sql_functions/usage_views.sql"
    drop_views_file = "wingtel/usage/sql_functions/usage_drop_views.sql"
    create_views = read_file_to_string(create_views_file)
    drop_views = read_file_to_string(drop_views_file)

    operations = [
        migrations.RunSQL(sql=create_views, reverse_sql=drop_views),
    ]
