# Generated by Django 2.2.1 on 2022-12-24 14:25

from django.db import migrations

from ..utils import read_file_to_string


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_add_usage_records"),
    ]
    create_triggers_file = "wingtel/usage/sql_functions/usage_triggers.sql"
    drop_triggers_file = "wingtel/usage/sql_functions/usage_drop_triggers.sql"
    create_triggers = read_file_to_string(create_triggers_file)
    drop_triggers = read_file_to_string(drop_triggers_file)
    operations = [
        migrations.RunSQL(sql=create_triggers, reverse_sql=drop_triggers),
    ]
