# Generated by Django 2.2.1 on 2021-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_auto_20210810_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bothusagerecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
