# Generated by Django 2.2.1 on 2021-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20210810_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='bothusagerecord',
            name='type_of_subscription',
            field=models.CharField(choices=[('att', 'Att'), ('sprint', 'Sprint')], default='att', max_length=100),
            preserve_default=False,
        ),
    ]
