# Generated by Django 2.2.1 on 2021-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_auto_20210810_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bothusagerecord',
            name='att_subscription_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bothusagerecord',
            name='sprint_subscription_id',
            field=models.IntegerField(null=True),
        ),
    ]
