# Generated by Django 2.2.1 on 2021-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_auto_20210810_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bothusagerecord',
            name='att_subscription_id',
        ),
        migrations.RemoveField(
            model_name='bothusagerecord',
            name='sprint_subscription_id',
        ),
        migrations.AddField(
            model_name='bothusagerecord',
            name='subscription_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bothusagerecord',
            name='type_of_subscription',
            field=models.CharField(choices=[('att', 'Att'), ('sprint', 'Sprint')], default='att', max_length=100),
            preserve_default=False,
        ),
    ]
