# Generated by Django 2.2.1 on 2021-08-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_subscriptions', '0003_auto_20210820_0626'),
        ('usage', '0008_auto_20210811_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausagerecord',
            name='att_subscription_id',
        ),
        migrations.RemoveField(
            model_name='datausagerecord',
            name='sprint_subscription_id',
        ),
        migrations.RemoveField(
            model_name='voiceusagerecord',
            name='att_subscription_id',
        ),
        migrations.RemoveField(
            model_name='voiceusagerecord',
            name='sprint_subscription_id',
        ),
        migrations.AddField(
            model_name='datausagerecord',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.Subscription'),
        ),
        migrations.AddField(
            model_name='voiceusagerecord',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.Subscription'),
        ),
    ]
