# Generated by Django 2.2.1 on 2021-08-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0010_remove_bothusagerecord_type_of_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bothusagerecord',
            name='subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.Subscription'),
        ),
    ]
